# Default values for jira-manager service.
replicaCount: 1
revisionHistoryLimit: 0

image:
  tag: ""

service:
  port: 9000

ingress:
  host: ""
  annotations: {nginx.ingress.kubernetes.io/proxy-read-timeout: 1800000}

resources:
  limits:
    memory: "512M"
  requests:
    memory: "512M"

java:
  debugEnabled: true
  initMemRation: 40
  maxMemRation: 70
  options: >-
     -Dconfig.resource=application-docker.conf
     -Dlogger.file=/opt/lib/logback-prod.xml
     -XshowSettings:vm
     -XX:+UnlockExperimentalVMOptions
     -XX:+UseCGroupMemoryLimitForHeap
     -XX:+PrintGCDetails
     -XX:+PrintGCDateStamps
     -Xloggc:/var/log/gc.log
     -XX:+UseGCLogFileRotation
     -XX:NumberOfGCLogFiles=10
     -XX:GCLogFileSize=32M

nonProxyHosts: "localhost|*.todo_intranet.ru"

config: ""

logstash: ""
