openapi: 3.0.0
info:
  version: 1.0.0
  title: jira-manager
paths:
  /api/jira-manager/updateLabels:
    post:
      tags:
      - jira-manager
      summary: Запрос updateLabels
      description: Запрос updateLabels
      responses:
        '200':
          description: Успешный запрос
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SupportManagerResponse'
        '400':
          description: Отсутсвует обязательный параметр
        '403':
          description: Доступ запрещен
        '500':
          description: Системное исключение
        '509':
          description: Превышен лимит времени на запрос
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UpdateLabelsRequest'
        description: ---
##
  /api/jira-manager/updateDeadLine:
    post:
      tags:
      - jira-manager
      summary: Запрос updateDeadLine
      description: Запрос updateDeadLine
      responses:
        '200':
          description: Успешный запрос
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SupportManagerResponse'
        '400':
          description: Отсутсвует обязательный параметр
        '403':
          description: Доступ запрещен
        '500':
          description: Системное исключение
        '509':
          description: Превышен лимит времени на запрос
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UpdateDeadlineRequest'
        description: ---
##
  /api/jira-manager/setScrum:
    put:
      tags:
      - jira-manager
      summary: SetScrum
      description: SetScrum
      responses:
        '200':
          description: Успешный запрос
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SupportManagerResponse'
        '400':
          description: Отсутсвует обязательный параметр
        '403':
          description: Доступ запрещен
        '500':
          description: Системное исключение
        '509':
          description: Превышен лимит времени на запрос
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/SetScrumRequest'
        description: ---
##
  /api/jira-manager/tasks:
    post:
      tags:
        - jira-manager
      summary: Отчеты
      description: Отчеты
      responses:
        '200':
          description: Успешный запрос
          content:
            application/json:
              schema:
                type: tasks
                items:
                  $ref: '#/components/schemas/JiraTask'
        '400':
          description: Отсутсвует обязательный параметр
        '403':
          description: Доступ запрещен (пока нет)
        '500':
          description: Системное исключение (пока нет)
        '509':
          description: Превышен лимит времени на запрос (пока нет)
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/TasksRequest'
        description: ---
##
  /api/jira-manager/report:
    get:
      tags:
      - jira-manager
      summary: Отчеты
      description: Отчеты
      parameters:
        - in: query
          name: issueId
          description: номер задачи (если не задан - задавать isFull, dateFrom, dateTo)
          required: false
          schema:
            type: string
        - in: query
          name: isFull
          description: признак полного отчета (true|false)
          required: false
          schema:
            type: boolean
        - in: query
          name: dateFrom
          description: date from, "dd-MM-yyyy HH:mm:ss"
          required: false
          schema:
            type: string
        - in: query
          name: dateTo
          description: date to, "dd-MM-yyyy HH:mm:ss"
          required: false
          schema:
            type: string
      responses:
        '200':
          description: Успешный запрос
          content:
            application/vnd.ms-excel:
              schema:
                type: string
                format: binary
        '400':
          description: Отсутсвует обязательный параметр
        '403':
          description: Доступ запрещен (пока нет)
        '500':
          description: Системное исключение (пока нет)
        '509':
          description: Превышен лимит времени на запрос (пока нет)
##
  /api/jira-manager/graphics:
    get:
      tags:
      - jira-manager
      summary: Аналитические данные для графиков
      description: Аналитические данные для графиков
      parameters:
        - in: query
          name: dateFrom
          description: date from, "dd-MM-yyyy"
          required: true
          schema:
            type: string
        - in: query
          name: dateTo
          description: date to, "dd-MM-yyyy"
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Успешный запрос
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GraphicsResponse'
        '400':
          description: Отсутсвует обязательный параметр
        '403':
          description: Доступ запрещен (пока нет)
        '500':
          description: Системное исключение (пока нет)
        '509':
          description: Превышен лимит времени на запрос (пока нет)
#######################################
#######################################
components:
  schemas:
    UpdateLabelsRequest:
      type: object
      description: Параметры для UpdateLabels
      properties:
        userName:
          type: string
          description: user Name
          example: 'user'
        password:
          type: string
          description: password
          example: 'password'
#######################################
#######################################
    UpdateDeadlineRequest:
      type: object
      description: Параметры для UpdateDeadline
      properties:
        userName:
          type: string
          description: user Name
          example: 'user'
        password:
          type: string
          description: password
          example: 'password'
    SetScrumRequest:
      type: object
      description: Параметры для SetScrum
      properties:
        userName:
          type: string
          description: user Name
          example: 'user'
        password:
          type: string
          description: password
          example: 'password'
#######################################
#######################################
    TasksRequest:
      type: object
      description: Параметры для генерации отчетов
      properties:
        userName:
          type: string
          description: логин jira (если не задано, используется из конфига)
          example: 'user'
        password:
          type: string
          description: пароль jira (если не задано, используется из конфига)
          example: 'password'
        issueId:
          type: string
          description: номер задачи (если не задано, обязательно задавать все три параметра- isFull, dateFrom, dateTo)
          example: 'TDS-123'
        isFull:
          type: boolean
          description: признак полного отчета (true|false)
          example: false
        dateFrom:
          type: string
          description: date from, dd-MM-yyyy HH:mm:ss
          example: '01-01-2001 12:00:00'
        dateTo:
          type: string
          description: date to, dd-MM-yyyy HH:mm:ss
          example: '01-01-2001 13:00:00'
#######################################
#######################################
    SupportManagerResponse:
      type: object
      description: Ответ на запрос jiraManager
      properties:
        error:
          type: string
          description: текст ошибки, если есть
          example: "Ошибка"
#######################################
    JiraTask:
      type: object
      description: Данные по задаче
      properties:
        code:
          type: string
        name:
          type: string
        status:
          type: string
        priority:
          type: string
        srnumber:
          type: string
        startDate:
          type: string
        closeDate:
          type: string
        comment:
          type: string
#######################################
    GraphicsResponse:
      type: object
      description: Агрегированные данные для графиков
      properties:
        jiraTaskStatusData:
          type: array
          items:
            $ref: '#/components/schemas/JiraAnalyticsData'
        jiraTaskNewStatusData:
          type: array
          items:
            $ref: '#/components/schemas/JiraAnalyticsData'
        jiraTaskOpenedClosedData:
          type: array
          items:
            $ref: '#/components/schemas/JiraAnalyticsData'
        jiraTaskOpenedRejectedData:
          type: array
          items:
            $ref: '#/components/schemas/JiraAnalyticsData'
#######################################
    JiraAnalyticsData:
      type: object
      description: Запись агрегированных данных для графика
      properties:
        date:
          type: string
          description: Дата
          example: '2017-08-25 15:05:24'
        TODO:
          type: Integer
          example: 1
        ANALYSIS:
          type: Integer
          example: 1
        DEVELOP:
          type: Integer
          example: 1
        ON_TEST:
          type: Integer
          example: 1
        WAITING_EXTERNAL:
          type: Integer
          example: 1
        ADD_INFO:
          type: Integer
          example: 1
        CLOSED:
          type: Integer
          example: 1
        CLOSED_WITHOUT_DEV:
          type: Integer
          example: 1
        INVALID:
          type: Integer
          example: 1